package interfaceGrafica;
/**
 *
 * @author gabriel.pagvelosa
 */
public class telaHome extends javax.swing.JFrame {
    public telaHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTelaDeFundoHome = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        produtos = new javax.swing.JMenu();
        btProdutos = new javax.swing.JRadioButtonMenuItem();
        fornecedores = new javax.swing.JMenu();
        btForn = new javax.swing.JRadioButtonMenuItem();
        contabilidade = new javax.swing.JMenu();
        btCalc = new javax.swing.JRadioButtonMenuItem();
        patrocinadores = new javax.swing.JMenu();
        btPatrocinadores = new javax.swing.JRadioButtonMenuItem();
        sobre = new javax.swing.JMenu();
        btSobre = new javax.swing.JRadioButtonMenuItem();
        sair = new javax.swing.JMenu();
        btSaida = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Home");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTelaDeFundoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeHome.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTelaDeFundoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 394, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTelaDeFundoHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        produtos.setText("Produtos");

        btProdutos.setSelected(true);
        btProdutos.setText("Tabela com produtos");
        btProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutosActionPerformed(evt);
            }
        });
        produtos.add(btProdutos);

        jMenuBar1.add(produtos);

        fornecedores.setText("Fornecedores");

        btForn.setSelected(true);
        btForn.setText("Fornecedores");
        btForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornActionPerformed(evt);
            }
        });
        fornecedores.add(btForn);

        jMenuBar1.add(fornecedores);

        contabilidade.setText("Contabilidade");

        btCalc.setSelected(true);
        btCalc.setText("Calculadora");
        btCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcActionPerformed(evt);
            }
        });
        contabilidade.add(btCalc);

        jMenuBar1.add(contabilidade);

        patrocinadores.setText("Patrocinadores");

        btPatrocinadores.setSelected(true);
        btPatrocinadores.setText("Patrocinadores");
        btPatrocinadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPatrocinadoresActionPerformed(evt);
            }
        });
        patrocinadores.add(btPatrocinadores);

        jMenuBar1.add(patrocinadores);

        sobre.setText("Sobre");

        btSobre.setSelected(true);
        btSobre.setText("Quem somos?");
        btSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSobreActionPerformed(evt);
            }
        });
        sobre.add(btSobre);

        jMenuBar1.add(sobre);

        sair.setText("Sair");

        btSaida.setSelected(true);
        btSaida.setText("Sair");
        btSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaidaActionPerformed(evt);
            }
        });
        sair.add(btSaida);

        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcActionPerformed
        // TODO add your handling code here:
        telaCalculadora calc = new telaCalculadora();
        calc.setVisible(true);
    }//GEN-LAST:event_btCalcActionPerformed

    private void btFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornActionPerformed
        // TODO add your handling code here:
        telaFornecedores forn = new telaFornecedores();
        forn.setVisible(true);
    }//GEN-LAST:event_btFornActionPerformed

    private void btSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSobreActionPerformed
        // TODO add your handling code here:
        telaSobre sobr = new telaSobre();
        sobr.setVisible(true);
    }//GEN-LAST:event_btSobreActionPerformed

    private void btProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutosActionPerformed
        // TODO add your handling code here:
        telaEstoque estoque = new telaEstoque();
        estoque.setVisible(true);
    }//GEN-LAST:event_btProdutosActionPerformed

    private void btPatrocinadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPatrocinadoresActionPerformed
        // TODO add your handling code here:
        telaPatrocinadores patr = new telaPatrocinadores();
        patr.setVisible(true);
    }//GEN-LAST:event_btPatrocinadoresActionPerformed

    private void btSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaidaActionPerformed
        // TODO add your handling code here:
        telaSaida sair = new telaSaida();
        sair.setVisible(true);
    }//GEN-LAST:event_btSaidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem btCalc;
    private javax.swing.JRadioButtonMenuItem btForn;
    private javax.swing.JRadioButtonMenuItem btPatrocinadores;
    private javax.swing.JRadioButtonMenuItem btProdutos;
    private javax.swing.JRadioButtonMenuItem btSaida;
    private javax.swing.JRadioButtonMenuItem btSobre;
    private javax.swing.JMenu contabilidade;
    private javax.swing.JMenu fornecedores;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu patrocinadores;
    private javax.swing.JMenu produtos;
    private javax.swing.JMenu sair;
    private javax.swing.JMenu sobre;
    private javax.swing.JLabel txtTelaDeFundoHome;
    // End of variables declaration//GEN-END:variables
}
